-- local actions = require "fzf-lua.actions"
--
-- require'fzf-lua'.setup {
--      width            = 0.95,            -- window width
--      col              = 0.5,             -- window col position (0=left, 1=right)
--      row              = 0.35,            -- window row position (0=top, 1=bottom)
--      height           = 0.50,            -- window height
-- }
