gui:
  showIcons: true
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
os:
  editCommand: 'nvim' # see 'Configuring File Editing' section
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
